LIST = [
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
    "It always seems impossible until it's done. – Nelson Mandela",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "The journey of a thousand miles begins with one step. – Lao Tzu",
    "Act as if what you do makes a difference. It does. – William James",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "To live a creative life, we must lose our fear of being wrong. – Joseph Chilton Pearce",
    "It is never too late to be what you might have been. – George Eliot",
    "We do not remember days, we remember moments. – Cesare Pavese",
    "Don’t wait. The time will never be just right. – Napoleon Hill",
    "Everything you can imagine is real. – Pablo Picasso",
    "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Our greatest glory is not in never falling, but in rising every time we fall. – Confucius",
    "In the middle of every difficulty lies opportunity. – Albert Einstein",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "The only impossible journey is the one you never begin. – Tony Robbins",
    "A journey of a thousand miles begins with a single step. – Lao Tzu",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
    "The best way to predict the future is to create it. – Abraham Lincoln",
    "Don’t count the days, make the days count. – Muhammad Ali",
    "If you can dream it, you can do it. – Walt Disney",
    "Opportunities don't happen, you create them. – Chris Grosser",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
    "We may encounter many defeats, but we must not be defeated. – Maya Angelou",
    "You must be the change you wish to see in the world. – Mahatma Gandhi",
    "You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne",
    "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Success is not in what you have, but who you are. – Bo Bennett",
    "Keep going. Everything you need will come to you at the perfect time. – Anonymous",
    "Everything you’ve ever wanted is on the other side of fear. – George Addair",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "Act as if what you do makes a difference. It does. – William James",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "Happiness depends upon ourselves. – Aristotle",
    "You don't have to be great to start, but you have to start to be great. – Zig Ziglar",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "If you want to live a happy life, tie it to a goal, not to people or things. – Albert Einstein",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
    "To live a creative life, we must lose our fear of being wrong. – Joseph Chilton Pearce",
    "Everything you can imagine is real. – Pablo Picasso",
    "The best way to predict the future is to create it. – Abraham Lincoln",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
    "It always seems impossible until it's done. – Nelson Mandela",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "The journey of a thousand miles begins with one step. – Lao Tzu",
    "Act as if what you do makes a difference. It does. – William James",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "To live a creative life, we must lose our fear of being wrong. – Joseph Chilton Pearce",
    "It is never too late to be what you might have been. – George Eliot",
    "We do not remember days, we remember moments. – Cesare Pavese",
    "Don’t wait. The time will never be just right. – Napoleon Hill",
    "Everything you can imagine is real. – Pablo Picasso",
    "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Our greatest glory is not in never falling, but in rising every time we fall. – Confucius",
    "In the middle of every difficulty lies opportunity. – Albert Einstein",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "The only impossible journey is the one you never begin. – Tony Robbins",
    "A journey of a thousand miles begins with a single step. – Lao Tzu",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
    "The best way to predict the future is to create it. – Abraham Lincoln",
    "Don’t count the days, make the days count. – Muhammad Ali",
    "If you can dream it, you can do it. – Walt Disney",
    "Opportunities don't happen, you create them. – Chris Grosser",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
    "We may encounter many defeats, but we must not be defeated. – Maya Angelou",
    "You must be the change you wish to see in the world. – Mahatma Gandhi",
    "You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne",
    "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
    "Success is not in what you have, but who you are. – Bo Bennett",
    "Keep going. Everything you need will come to you at the perfect time. – Anonymous",
    "Everything you’ve ever wanted is on the other side of fear. – George Addair",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "Happiness depends upon ourselves. – Aristotle",
    "You don't have to be great to start, but you have to start to be great. – Zig Ziglar",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "If you want to live a happy life, tie it to a goal, not to people or things. – Albert Einstein",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
    "To live a creative life, we must lose our fear of being wrong. – Joseph Chilton Pearce",
    "Everything you can imagine is real. – Pablo Picasso",
    "The best way to predict the future is to create it. – Abraham Lincoln",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
    "It always seems impossible until it's done. – Nelson Mandela",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "The journey of a thousand miles begins with one step. – Lao Tzu",
    "Act as if what you do makes a difference. It does. – William James",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "To live a creative life, we must lose our fear of being wrong. – Joseph Chilton Pearce",
    "It is never too late to be what you might have been. – George Eliot",
    "We do not remember days, we remember moments. – Cesare Pavese",
    "Don’t wait. The time will never be just right. – Napoleon Hill",
    "Everything you can imagine is real. – Pablo Picasso",
    "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Our greatest glory is not in never falling, but in rising every time we fall. – Confucius",
    "In the middle of every difficulty lies opportunity. – Albert Einstein",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "The only impossible journey is the one you never begin. – Tony Robbins",
    "A journey of a thousand miles begins with a single step. – Lao Tzu",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
    "The best way to predict the future is to create it. – Abraham Lincoln",
    "Don’t count the days, make the days count. – Muhammad Ali",
    "If you can dream it, you can do it. – Walt Disney"
]

def quote():
    return LIST

def emoji():
    return [
    "😀", "😁", "😂", "🤣", "😃", "😄", "😅", "😆", "😉", "😊", "😋",
    "😎", "😍", "😘", "🥰", "😗", "😙", "😚", "😌", "😜", "😝", "😛",
    "🤑", "😎", "🤓", "😏", "😞", "😟", "😠", "😡",
    "😢", "😭", "😤", "😳", "😱", "😨", "😰", "😥", "😓", "🤗",
    "🤔", "🤭", "🤫", "🤥", "😶", "😐", "😑", "😬", "🙄", "😯",
    "😦", "😧", "😮", "😲", "😴", "🤤", "😪", "😷", "🤒", "🤕",
    "🤢", "🤮", "🤧", "🥳", "🥺", "😵", "💫", "🤯", "😷", "🥴",
    "😇", "🤠", "🥸", "💀", "☠️", "👻",
    "👽", "🤖", "🎃", "🎄", "🎆", "🎇", "🧨", "💥", "💫", "✨",
    "🌟", "🌈", "🌞", "🌝", "🌛", "🌜", "🌚", "⭐", "🌙", "🌌",
    "🌍", "🌎", "🌏", "💫", "🌱", "🌷", "🌸", "💐", "🌺",
    "🌻", "🌼", "🌹", "🥀", "🍀", "🍁", "🍂", "🍃", "🌾", "🌵", "🌴", "🌳", "🌲", "🌴"]

def codesite():
    return ["https://leetcode.com", "https://codewars.com", "https://hackerrank.com", "https://codeforces.com", "https://geeksforgeeks.com", "i use linux btw", "https://fedoraproject.org", "💫 You are gonna have a lucky day"]

def feelingLucky():
    return ["I'm Feeling Curious",
    "I'm Feeling Doodly",
    "I'm Feeling Artistic",
    "I'm Feeling Trendy",
    "I'm Feeling Playful",
    "I'm Feeling Adventurous",
    "I'm Feeling Puzzled",
    "I'm Feeling Astronomical",
    "I'm Feeling Lucky",
    "I'm Feeling Generous",
    "I'm Feeling Hungry",
    "I'm Feeling Lucky"]